- CHANGELOG.md
- ecs/entity.go
- ecs/entity_pool.go
- ecs/entity_pool_test.go
- ecs/entity_test.go
- ecs/world.go
- ecs/world_test.go
> Reserved Zero Entity

- CHANGELOG.md
- ecs/archetype.go
- ecs/archetype_test.go
- ecs/config.go
- ecs/config_test.go
- ecs/entity_pool.go
- ecs/entity_pool_test.go
- ecs/world.go
- profile/main/profile.go
Add `Config` to allow for configuration of the world
Current only setting is storage capacity increment
> World configuration

- CHANGELOG.md
- ecs/query.go
- ecs/query_test.go
- ecs/world.go
Returns the total number of matched entities.
> Add method Count to type Query

- CHANGELOG.md
- ecs/archetype.go
Use one more indirection to reduce archetype size
> Smaller archetypes

- CHANGELOG.md
- ecs/archetype.go
- ecs/archetype_test.go
- ecs/storage.go
- ecs/test_types.go
- ecs/types.go
- ecs/world.go
- ecs/world_test.go
Adds these methods to `World`:
```go
func (w *World) Exchange(entity Entity, add []ID, rem []ID)
func (w *World) Assign(entity Entity, id ID, comp interface{}) unsafe.Pointer
func (w *World) AssignN(entity Entity, comps ...Component)
```
> Component exchange and assignment

- CHANGELOG.md
- README.md
- ecs/archetype.go
- ecs/bitmask.go
- ecs/bitmask_test.go
- ecs/paged.go
- ecs/paged_test.go
- ecs/query.go
- ecs/types.go
- ecs/world.go
- ecs/world_test.go
* Update changelog
* Update readme
* Make `bitMask` not exported
> Release v0.2.0

- CHANGELOG.md
- ecs/archetype.go
- ecs/archetype_test.go
- ecs/query.go
- ecs/world.go
* Move component check from world to archetype
* Add unsafe but faster archetype access for use by queries
> Optimize component access in archetypes

- README.md
- ecs/query_generic.go
Add a section on generics to the README
> Document generics

- CHANGELOG.md
- ecs/query.go
- ecs/query_test.go
- examples/base/main.go
- examples/generic/main.go
- generic/query_generic.go
- generic/query_generic_test.go
With and Without methods for generic queries.
> Query with/without

- CHANGELOG.md
- benchmark/iterate/arche_test.go
- generic/query_generic.go
- generic/query_generic_test.go
- generic/util.go
* Compile generic queries to masks in first build
* Make generic query builder pointer types
> Precompile generic queries

- CHANGELOG.md
- ecs/query.go
- ecs/query_test.go
- generic/query_generic_test.go
Fix ecs Without filter to exclude all components, not any
> Fix exclusion filter

- CHANGELOG.md
- ecs/query.go
- ecs/query_test.go
- ecs/world.go
- ecs/world_test.go
- examples/base/main.go
- examples/filter/main.go
- examples/generic/main.go
* Add the possibility to get an entity's mask from world and queries
> Get entity bitmask

- .github/workflows/benchmarks.yml
- .github/workflows/tests.yml
- README.md
- examples/filter/main.go
- examples/generic/main.go
- examples/readme/main.go
* Tweak examples
* Add the README example to examples folder for testing
> Tweak examples

- CHANGELOG.md
- benchmark/add/arche_test.go
- benchmark/iterate/arche_test.go
- ecs/archetype.go
- ecs/world.go
- ecs/world_test.go
* Adds the option to register a function to get notified on entity or component changes
> Change notifications

- CHANGELOG.md
- README.md
- benchmark/iterate/arche_test.go
- benchmark/move/ggecs_test.go
- benchmark/profile/exchange/main.go
- benchmark/profile/iter/main.go
- ecs/archetype.go
- ecs/archetype_test.go
- ecs/entity_pool.go
- ecs/storage.go
- ecs/storage_test.go
- ecs/types.go
- ecs/world.go
- examples/generic/main.go
- examples/locked_world/main.go
- examples/readme/main.go
- generic/generate/query.go.txt
- generic/query_generated.go
- generic/query_test.go
> Optimize Add/Remove/Exchange

- .github/workflows/tests.yml
- CHANGELOG.md
- benchmark/iterate/arche_test.go
- benchmark/profile/world/main.go
- ecs/archetype.go
- ecs/bitmask64.go
- ecs/bitmask_test.go
- ecs/entity.go
- ecs/entity_pool.go
- ecs/stats/stats.go
- ecs/world.go
- examples/random_access/main.go
- examples/world_stats/main.go
Adds examples, adds reserved memory to world and archetype stats.
Fixes #80
> More examples, more stats

- CHANGELOG.md
- benchmark/common/components.go
- benchmark/iterate/arche_test.go
- benchmark/iterate/ggecs_test.go
- ecs/archetype.go
- ecs/query.go
- ecs/world.go
* Speed up component check by nil pointer comparison instead of mask check.
* Speed up iteration by making the code in `Query.Next()` more inlining-friendly.
> World component access optimization

- ecs/archetype_test.go
- ecs/storage_test.go
- ecs/types_test.go
Add work to benchmark loops to avoid compiler optimization
> Fair benchmarks

- generic/query_test.go
Add test for getting optional components in generic queries
> Extend generic query tests

- CHANGELOG.md
- benchmark/profile/iter/main.go
- ecs/archetype.go
- ecs/archetype_test.go
- ecs/registry.go
- ecs/storage.go
- ecs/world.go
- ecs/world_test.go
- Split archetype graph out of archetypes
- Reduce size of component registry by using slice instead of fixed-size array
Fixes #112
> Archetype graph

- CHANGELOG.md
- benchmark/arche/add/arche_test.go
- ecs/world.go
Avoid copying entity index struct by using pointers.
> No entity index copy

- CHANGELOG.md
- benchmark/arche/add/ggecs_test.go
- benchmark/arche/iterate/ggecs_test.go
- benchmark/arche/move/ggecs_test.go
- benchmark/competition/pos_vel/ggecs_test.go
- benchmark/go.mod
- benchmark/go.sum
Upgrade [go-gameengine-ecs](https://github.com/marioolofo/go-gameengine-ecs) to v0.9.0 in benchmarks
> Upgrade go-gameengine-ecs in benchmarks

- CHANGELOG.md
- generic/generate/map.go.txt
- generic/generate/query.go.txt
- generic/map_generated.go
- generic/query_generated.go
- generic/util.go
* Remove wrapped structs
* Add hint to further query methods in generic queries
> Tweak generics internal

- README.md
Fix mask in ascii chart, add 'match' to one of the match arrows.
> Fix and amend archetypes ASCII chart

- .github/workflows/tests.yml
- CHANGELOG.md
- examples/systems/main.go
Adds an example to demonstrate how to implement classical ECS systems
> Systems example

- CHANGELOG.md
- ecs/archetype.go
- ecs/archetype_test.go
- ecs/bit_pool.go
- ecs/bit_pool_test.go
- ecs/entity_pool.go
- ecs/entity_pool_test.go
- ecs/resources.go
- ecs/resources_test.go
- ecs/world.go
- ecs/world_test.go
Implements `World.Reset()` for more efficient systematic simulations.
> World reset

- CHANGELOG.md
- ecs/query.go
- ecs/query_test.go
* speed up archetype mask checks by casting to basic filters
> Optimize archetype mask checks

- CHANGELOG.md
- ecs/archetype.go
- ecs/archetype_test.go
- ecs/batch.go
- ecs/batch_test.go
- ecs/bitmask.go
- ecs/bitmask_test.go
- ecs/query.go
- ecs/world.go
- ecs/world_test.go
Adds batch-create and batch-remove entities.
Fixes #141
Fixes #142
> Batch operations

- CHANGELOG.md
- ecs/world.go
- generic/generate/main.go
- generic/generate/map.go.txt
- generic/map_generated.go
- generic/map_generated_test.go
Makes batch creation and removal of entities possible using generic mappers.
> Generic batch operations

- CHANGELOG.md
- ecs/batch.go
- ecs/batch_test.go
- ecs/world.go
- ecs/world_test.go
- generic/generate/map.go.txt
- generic/map_generated.go
- generic/map_generated_test.go
* Methods like `NewEntities` don't return a query.
* For creation with a query, there is `NewEntitiesWith` etc.
> Optional queries from batch-creation

- ecs/archetype.go
- ecs/bit_pool.go
- ecs/bit_pool_test.go
- ecs/bitmask.go
- ecs/config.go
- ecs/event.go
- ecs/query.go
- ecs/types.go
- ecs/util.go
- ecs/util_test.go
- ecs/world.go
- ecs/world_test.go
* Bundle locks and bit pool in a separate struct
* Document more struct fields
> Cleanup docs and code

- .github/workflows/tests.yml
- CHANGELOG.md
- ecs/batch.go
- ecs/world.go
- ecs/world_test.go
- examples/batch_ops/main.go
- generic/generate/map.go.txt
- generic/map_generated.go
- generic/map_generated_test.go
* Batch-remove methods return the number of removed entities
* Add batch operations example
> Batch-remove methods return the number of removed entities

- examples/base/main.go
- examples/batch_ops/main.go
- examples/locked_world/main.go
- examples/random_access/main.go
- examples/systems/main.go
- examples/world_stats/main.go
- Fix systems example
- Tweak comments in examples
> Fix and tweak examples

- README.md
- benchmark/competition/add_remove/plot.py
- benchmark/competition/pos_vel/plot.py
> Median values as text in benchmark plots

- README.md
- benchmark/competition/add_remove/arche_test.go
- benchmark/competition/add_remove/donburi_test.go
- benchmark/competition/add_remove/ento_test.go
- benchmark/competition/add_remove/ggecs_test.go
* Iterate once before benchmarking in add/remove example to exclude allocations
> Fair benchmarks - exclude allocations

- ecs/entity.go
- ecs/query.go
- ecs/world.go
* add docs code examples and references
> Documentation tweaks

- ecs/batch.go
- examples/batch_ops/main.go
- generic/generate/map.go.txt
- generic/map_generated.go
* add examples for batch operations
* fix docstring on `MapX.RemoveEntities`
> Batch processing examples

- CHANGELOG.md
- ecs/batch.go
- ecs/batch_test.go
- ecs/bitmask.go
- ecs/bitmask_test.go
- ecs/world_test.go
- examples/batch_ops/main.go
- generic/generate/map.go.txt
- generic/map_generated.go
> Rename Mask.Exact to Mask.Exclusive

- ecs/archetype.go
- ecs/cache.go
- ecs/cache_test.go
- ecs/event.go
- ecs/event_test.go
- ecs/world.go
- ecs/world_test.go
- diverse code cleanups
- optimize archetype creation a bit, by faster extraction of IDs from mask
- extend docs on events
> Code cleanup, optimize archetype creation, event docs

- ARCHITECTURE.md
- README.md
move out architecture, less features
> Simplify the README

- CHANGELOG.md
- ecs/archetype.go
- ecs/archetype_test.go
- ecs/archetypes.go
- ecs/archetypes_test.go
- ecs/cache.go
- ecs/entity.go
- ecs/query.go
- ecs/stats/stats.go
- ecs/util.go
- ecs/util_test.go
- ecs/world.go
- ecs/world_test.go
- generic/compiled.go
> Remove archetypes for dead entity relation targets

- CHANGELOG.md
- ecs/query.go
- ecs/world.go
- ecs/world_test.go
> Optimize `RelationFilter`: Query archetype directly instead of iterating node

- CHANGELOG.md
- ecs/archetypes.go
- ecs/world.go
- generic/generate/map.go.txt
- generic/map_generated.go
- generic/map_generated_test.go
Add method `NewWith` to generic maps
> Add generic maps mathod `NewWith`

- CHANGELOG.md
- ecs/builder.go
- generic/compiled.go
- generic/generate/main.go
- generic/generate/query.go.txt
- generic/query_generated.go
- generic/util.go
Check for relation in generic queries only after relation component change
> Optimize generic relation queries

- .github/workflows/tests.yml
- ARCHITECTURE.md
- CHANGELOG.md
- README.md
- ecs/archetype.go
- ecs/builder.go
- ecs/filter.go
- ecs/relation.go
- ecs/relation_test.go
- ecs/world.go
- examples/relations/main.go
> Document entity relations

- CHANGELOG.md
- ecs/archetype.go
- ecs/query.go
- ecs/stats/stats.go
- ecs/stats/stats_test.go
- ecs/world.go
- ecs/world_test.go
> Adapt world stats for node-based archetype management

- .github/workflows/tests.yml
- CHANGELOG.md
- README.md
- benchmark/arche/fragmentation/arche_test.go
- benchmark/arche/iterate/arche_test.go
- ecs/archetype.go
- ecs/archetypes.go
- ecs/archetypes_test.go
- ecs/cache.go
- ecs/cache_test.go
- ecs/query.go
- ecs/query_test.go
- ecs/world.go
> Cache nodes instead of archetypes

- benchmark/competition/relations/plot.py
> Benchmark plot with children on x axis and parents as line styles

- CHANGELOG.md
- ecs/bitmask.go
- ecs/cache.go
- ecs/doc.go
- ecs/filter.go
- ecs/world.go
- filter/doc.go
- filter/filter.go
- generic/doc.go
add outline to each doc.go, extend docs for world, filters and cache
> Add ouline to all package docks, tweak docstrings

- CHANGELOG.md
- generic/generate/main.go
- generic/map_generated.go
- generic/map_generated_test.go
- generic/mask.go
- generic/mask_test.go
- generic/query_generated.go
- generic/query_test.go
Extend generic API to up to 12 components
> Twelve (12) generic components

- CHANGELOG.md
- ecs/event.go
- ecs/event_test.go
- ecs/util.go
- ecs/util_test.go
- ecs/world.go
- ecs/world_examples_test.go
- ecs/world_test.go
- examples/events/main.go
- listener/callback.go
- listener/dispatch.go
- listener/util.go
- listener/util_test.go
* use saparate masks for component addition and removal -- was not taken into account correctly
* fix component subscription logic -- some relation subscriptions could get lost
* tweak docs of listener implementations
> Fix component subscription logic, tweak docs

- CHANGELOG.md
> Prepare release v0.10.0

- CHANGELOG.md
- ecs/pool.go
- ecs/query_test.go
- ecs/registry.go
- ecs/util.go
- generic/util.go
Improves error messages on:
- Running out of component or resource types
- Running out of World locks
- Unbalanced World unlock
Adds some tests on properly closed queries to solve #362
> Improve error messages

- BENCHMARKS.md
- CHANGELOG.md
- README.md
- benchmark/table/README.md
> Link benchmarking code in `README.md` and benchmarking tables

- docs/content/user-guide/entities/entities_test.go
- docs/content/user-guide/entities/index.md
- docs/content/user-guide/events/index.md
- docs/content/user-guide/filters/filters_test.go
- docs/content/user-guide/filters/index.md
- docs/content/user-guide/queries/index.md
- docs/content/user-guide/relations/index.md
- docs/content/user-guide/relations/relations_example_test.go
- docs/content/user-guide/relations/relations_test.go
- docs/content/user-guide/resources/index.md
- docs/content/user-guide/world-access/access_test.go
- docs/content/user-guide/world-access/index.md
- docs/layouts/partials/custom-header.html
- docs/layouts/shortcodes/api.html
- docs/static/css/style.css
Write chapters on world entity access and entity relations. Tweak other chapters.
> Arche user manual, 2/x

- docs/content/background/architecture.md
- docs/content/background/benchmarks.md
- docs/content/background/design.md
- docs/content/background/ecs.md
- docs/content/user-guide/batch-ops/batch_test.go
- docs/content/user-guide/batch-ops/index.md
- docs/content/user-guide/events/events_listener_test.go
- docs/content/user-guide/events/events_test.go
- docs/content/user-guide/events/index.md
- docs/content/user-guide/relations/index.md
- docs/content/user-guide/resources/index.md
- docs/content/user-guide/resources/resources_test.go
- docs/content/user-guide/tools/index.md
- docs/layouts/shortcodes/api.html
- docs/layouts/shortcodes/code.html
- generic/_generate/map.go.txt
- generic/map_generated.go
Wrote chapters on batch operations, relations, resources and events.
> Arche user manual, 3/x

- docs/content/_index.md
- docs/content/background/architecture.md
- docs/content/guide/performance/index.md
- docs/content/guide/stats/index.md
- ecs/functions_test.go
- Add chapter with performance tips
- Add benchmarks for `ComponentID` and `TypeID`
> Performance Tips

- benchmark/table/entities.go
- benchmark/table/query.go
- benchmark/table/world.go
Adds the following to the benchmark tables:
- Query.Entity
- Entity.IsZero
- World.GetUnchecked
- World.HasUnchecked
> Extend benchmark tables

- ecs/entity.go
- ecs/entity_test.go
When integrating with external systems (network in this case).  Need a read only way to check Entities ID and equality.
> Add entity read access

- CHANGELOG.md
- _examples/base/main.go
> Fix component type in examples/base

- CHANGELOG.md
- benchmark/table/components.go
- benchmark/table/entities.go
- generic/_generate/main.go
- generic/_generate/map.go.txt
- generic/map.go
- generic/map_generated.go
- generic/map_generated_test.go
> Optimize generic Assign and NewWith

- CHANGELOG.md
- docs/content/guide/entities/index.md
- docs/content/guide/queries/index.md
- docs/content/guide/world-access/index.md
- ecs/query.go
- ecs/world.go
- generic/_generate/map.go.txt
- generic/_generate/query.go.txt
- generic/map.go
- generic/map_generated.go
- generic/query_generated.go
> Add notes on entity and component pointer usage to docs and user guide
