CHANGELOG.md
ecs/bit_pool.go
ecs/bit_pool_test.go
ecs/entity_pool.go
ecs/query.go
ecs/world.go
ecs/world_test.go

Queries lock the world, and unlock it when iteration is done.
Each query has a lock bit to track individual query locks.
Fixes #12

Querys lock the World

---

CHANGELOG.md
benchmark/iterate/arche_test.go
doc.go
ecs/archetype.go
ecs/archetype_test.go
ecs/query.go
ecs/query_test.go
ecs/storage.go
ecs/storage_test.go
ecs/world.go
profile/main/profile.go

Change `Query` iterator to avoid allocations as well as indexing into a slice of archetypes.

Optimize query iteration

---

CHANGELOG.md
README.md
ecs/entity.go
ecs/paged.go
ecs/paged_test.go
ecs/world.go
ecs/world_test.go

Use pages memory to store archetypes, use pointers instead of indices in entity list.
Pages are a minimal ovrhead, but they make it possible to store refs to artifacts. Speeds up component access through the world/using an entity ID by up to 30%.

Paged archetypes

---

CHANGELOG.md
ecs/archetype.go
ecs/world.go
ecs/world_test.go

Implements an archetype graph for faster lookup of transitions
Fixes #17

Archetype graph

---

benchmark/iterate/arche_test.go
generic/generate/main.go
generic/generate/map.go.txt
generic/generate/query.go.txt
generic/generate/query_get.go.txt
generic/generate/query_getall.go.txt
generic/map_generated.go
generic/query_generated.go
generic/query_test.go
generic/util.go

Remove query methods `Get1`, `Get2`, ...
Builder methods `With` and `Optional` provide sufficient flexibility here.

Simplify generic queries

---

ecs/archetype.go
ecs/archetype_test.go
ecs/query.go

Remove unsafe getter from archetype (problem with optional comps, minimal overhead)

Remove `archetype.GetUnsafe()`

---

ecs/archetype.go

* Avoid repeated array indexing in archetype access

Optimize archetype access

---

CHANGELOG.md
ecs/world.go
ecs/world_test.go

* `EntityEvent` has more consistent values when an entity is removed
* `EntityEvent.NewMask` is zero
* `EntityEvent.Removed` is contains all former components
* `EntityEvent.Current` is `nil`

More consistent `EntityEvent` values on removed entity

---

.github/workflows/tests.yml
CHANGELOG.md
ecs/query.go
ecs/query_test.go
ecs/world.go
examples/random_sampling/main.go

`Query` has methods `Count()` and `Step(int)`, primarily for effective random sampling.
Alternative for #118.
Allows only forward jumps and counts, but looks generally better.

Query count and step

---

CHANGELOG.md
ecs/archetype.go
ecs/archetype_test.go
ecs/entity.go
ecs/query.go
ecs/storage.go
ecs/storage_test.go
ecs/world.go

* Reduce size of `storage`
* Avoid integer conversions by more us of `uintptr`
* Move nil check from archetypes to storage

Minor component storage optimization

---

CHANGELOG.md
ecs/archetype.go
ecs/world_test.go

Set component memory to zero when removing from or resetting archetype.

Bugfix: Allow GC on pointers in removed components

---

CHANGELOG.md
benchmark/arche/resources/arche_test.go
ecs/resources.go
ecs/resources_test.go
ecs/world.go
ecs/world_test.go
examples/resources/main.go
generic/resource.go

An object to handle resources can now be obtained via `world.Resources()`.

Move resource handling out of the world

---

CHANGELOG.md
ecs/archetype.go
ecs/archetype_test.go
ecs/batch.go
ecs/event.go
ecs/query.go
ecs/world.go
ecs/world_test.go
generic/generate/map.go.txt
generic/map_generated.go

Instead of notifying before returning the query created by batch-creation, notification is delayed until the query is closed. This brings two advantages:
* Notification occurs after the user changed/initialized the newly created entities
* The engine does not need to be locked during notifications
Further changes:
* `World.Reset()` does no longer remove the listener

Notify after batch-creation query

---

CHANGELOG.md
ecs/archetype.go
ecs/util.go
ecs/util_test.go
ecs/world.go
ecs/world_test.go

Reserve sufficient memory for all entities to add ad once, not in increments

Optimize entity batch-allocation

---

CHANGELOG.md
filter/filter.go
filter/filter_test.go

Removes inversion methods `filter.ALL.Not()` and `filter.ANY.Not()`, for consistency with `Mask.Not`.

Filter API cleanup

---

CHANGELOG.md
ecs/batch_test.go
ecs/event.go
ecs/event_test.go
ecs/world.go
ecs/world_test.go
examples/change_listener/main.go

World listener takes a pointer instead of a copied event struct.

EntityEvent pointer for listener

---

ecs/query.go
ecs/resources.go

Make archetypeIter fields private

Hide accidentially exposed embedded fields

---

CHANGELOG.md
benchmark/arche/move/arche_test.go
benchmark/arche/move/ggecs_test.go
ecs/archetype.go
ecs/archetype_test.go
ecs/world.go

* More efficiently clear the memory of removed components, with 2-3x speedup
* Do not clear when allocating, as it is already zero

More efficiently clear the memory of removed components

---

.github/workflows/benchmarks.yml
CHANGELOG.md
README.md
benchmark/competition/add_remove/arche_test.go
benchmark/competition/add_remove/doc.go
benchmark/competition/add_remove/donburi_test.go
benchmark/competition/add_remove/ento_test.go
benchmark/competition/add_remove/ggecs_test.go
benchmark/competition/add_remove/plot.py
benchmark/competition/pos_vel/plot.py
generic/generate/map.go.txt
generic/map_generated.go

* Avoid slice allocations in generic mapper methods that use varags
* Add a competition benchmark for adding and removing components

No alloc in generics, add/remove benchmarks

---

CHANGELOG.md
README.md
benchmark/arche/common/components.go
benchmark/arche/iterate/arche_test.go
benchmark/arche/iterate/ggecs_test.go
benchmark/profile/many_arch/main.go
ecs/archetype.go
ecs/cache.go
ecs/cache_test.go
ecs/paged.go
ecs/query.go
ecs/query_test.go
ecs/resources.go
ecs/types_test.go
ecs/world.go
ecs/world_test.go
generic/compiled.go
generic/generate/query.go.txt
generic/query_generated.go
generic/query_test.go

Introduces cached filters.
Filters are registered to the world, and the world keeps track of the relevant archetypes. When a query is created from a cached filter, the managed list of archetypes is used, and no mask checks are required during iteration.
However, this brings a performance advantage only for this case:
* many archetypes
* only a few entities to iterate, that are only in a few archetypes (or a single one)
Not sure if this is really worth the additional API and code.
Fixes #177
```
BenchmarkFilterUncached_1of16_100-2        	 3118692	       384.0 ns/op	       0 B/op	       0 allocs/op
BenchmarkFilterUncached_1of16_1_000-2      	  507350	      2312 ns/op	       0 B/op	       0 allocs/op
BenchmarkFilterUncached_1of16_10_000-2     	   55030	     22013 ns/op	       0 B/op …
```

Cached filters

---

CHANGELOG.md
ecs/query.go
ecs/query_test.go
ecs/world.go
ecs/world_test.go

* Avoid type checks in iteration over archetypes
* Merge `archetypeIter` into `Query`

Query cleanup

---

CHANGELOG.md
ecs/query.go

- Speed up counting in cached queries by not checking the mask

Optimize counting in cached queries

---

CHANGELOG.md
ecs/paged.go
ecs/paged_test.go
ecs/world.go
ecs/world_test.go

Use slices instead of arrays inside paged archetype list to ensure pointer persistence.

Bugfix: Archetype pointer persistence

---

CHANGELOG.md
benchmark/arche/build/arche_test.go
ecs/archetype.go
ecs/cache.go
ecs/id_map.go
ecs/id_map_test.go
ecs/world_test.go

`idMap ` is a data structure meant for fast lookup by component ID keys, while being memory-efficient.
Access time is around 2ns, compared to 0.5ns for array access and 20ns for `map[int]T`.
The memory footprint is reduced by using chunks, and only allocating chunks if they contain a key.

Efficient data structure for mapping from component IDs

---

CHANGELOG.md
benchmark/arche/relations/child_test.go
benchmark/arche/relations/doc.go
benchmark/arche/relations/parent_array_test.go
benchmark/arche/relations/parent_list_test.go
benchmark/arche/relations/parent_slice_test.go
ecs/world.go

Add benchmarks for different ways to implement entity relationships:
- Children know their parent entity
- Parents have an array of child entities
- Parents have a slice of child entities
- Children form an implicit linked lists, parents know the first child

Benchmark entity relationships

---

CHANGELOG.md
ecs/entity.go
ecs/entity_test.go

- add hint on copy to entity docs
- add doc examples
- benchmark for IsZero

Extend entity docs - copy hint, examples

---

CHANGELOG.md
README.md
benchmark/profile/world/main.go
ecs/pool.go
ecs/world.go
ecs/world_test.go

All world methods with an entity as argument panic on a dead/recycled entity; causes 0.5ns slower `World.Get(Entity)`

Fix: Always panic on dead entity

---

CHANGELOG.md
benchmark/arche/iterate/arche_test.go
benchmark/arche/iterate_world/arche_test.go
ecs/world.go
ecs/world_test.go
generic/generate/main.go
generic/generate/map.go.txt
generic/map.go
generic/map_generated.go
generic/map_generated_test.go
generic/map_test.go

Mitigate performance degradation introduced by #216:
* Adds methods `World.GetUnsafe` and `World.HasUnsafe` as optimized variants for known static entities
* Adds method `MapX.GetUnsafe` to all generic mappers, as equivalent to previous point
* Adds methods `Map.GetUnsafe` and `Map.HasUnsafe` to generic `Map`, as equivalent to previous points

Unsafe component access with World.GetUnsafe/HasUnsafe

---

CHANGELOG.md
README.md
benchmark/profile/world/main.go
ecs/pool.go
ecs/pool_test.go

* Optimize entity alive check by only comparing the generation, but don't check for zero entity ID
* Set next version in CHANGELOG to v0.7.0
Fixes #218

Optimize entity alive check

---

CHANGELOG.md
ecs/archetype.go
ecs/archetypes.go
ecs/archetypes_test.go
ecs/pool.go
ecs/query.go
ecs/util.go
ecs/util_test.go
ecs/world.go
ecs/world_test.go

* Reduce memory size of `Query` and internal archetype list by 8 bytes

Memory optimizations: Query and internal archetype list

---

CHANGELOG.md
ecs/archetype.go
ecs/archetype_test.go
ecs/world.go
ecs/world_test.go

Moved properties shared by relation archetypes to the parent node.
Fixes #236

Archetype size optimization

---

CHANGELOG.md
generic/compiled.go
generic/generate/query.go.txt
generic/query_generated.go
generic/query_test.go

* Prevent modifying registered generic filters
* Don't fully recompile after changing relation target

Lock registered filters, partial recompile

---

ecs/archetype.go
ecs/archetype_test.go
ecs/world.go
ecs/world_test.go
examples/relations/main.go

* Relation target got lost when moving between nodes/archetypes.
* Update archetype count in node stats update

Bugfix: Move relation target when exchanging components

---

CHANGELOG.md
ecs/archetype.go
ecs/archetypes.go
ecs/batch.go
ecs/builder.go
ecs/builder_test.go
ecs/query.go
ecs/relation_stress_test.go
ecs/world.go
ecs/world_benchmark_test.go
ecs/world_test.go
examples/batch_ops/main.go
generic/generate/map.go.txt
generic/map_generated.go

* Re-introduce `World.Batch` for batch-processing of entities (add/remove/exchange)
* New method `Builder.Add` for adding components with a target to entities
Fixes #263

Batch-exchange and add with target

---

CHANGELOG.md
benchmark/arche/relations/relation_test.go
ecs/archetypes.go
ecs/batch.go
ecs/event.go
ecs/event_test.go
ecs/filter.go
ecs/query.go
ecs/relation_examples_test.go
ecs/relation_stress_test.go
ecs/util.go
ecs/world.go
ecs/world_examples_test.go
ecs/world_test.go
examples/relations/main.go
generic/compiled.go

* add possibility to batch-set entity relations
* make `RelationFilter` a function instead of a struct

Batch-set entity relation, RelationFilter to function

---

CHANGELOG.md
benchmark/arche/relations/relation_test.go
ecs/query.go
ecs/query_test.go
ecs/relation_benchmark_test.go
generic/compiled.go
generic/generate/query.go.txt
generic/query_generated.go
generic/query_test.go
generic/relation_benchmark_test.go
generic/util.go

* Generic filters can use `filter.Query(&world, target)` optionally
* Target argument in generic filter `WithRelation` is optional
* Remove query and generic query `RelationUnchecked` (runtime overhead vanished for some reason)
* Remove generic filter method `Filter`

Rework generic query access

---

benchmark/arche/common/components.go
benchmark/arche/iterate/arche_test.go
ecs/cache_test.go
ecs/filter.go
ecs/query.go
ecs/world.go
filter/doc.go
filter/filter.go

* Don't check relation archetype match if not a relation filter
* Relation filters can only be outermost filter (except for `CachedFilter`)
* Add benchmarks for iteration over many targets, fix 1k arches benchmarks
TODO
* Could be more efficient, as iterating archetypes in a node seems faster than iterating the prepared list of archetypes now

Optimize archetype iteration

---

CHANGELOG.md
benchmark/arche/relations/child_test.go
benchmark/arche/relations/parent_list_test.go
benchmark/arche/relations/parent_slice_test.go
benchmark/arche/relations/relation_cached_test.go
benchmark/arche/relations/relation_test.go
benchmark/competition/array_of_structs/arche_test.go
benchmark/competition/array_of_structs/array_of_pointers_test.go
benchmark/competition/array_of_structs/array_of_structs_test.go
benchmark/competition/array_of_structs/linked_list_test.go

* Use for loop with counter in AoS competition benchmarks, to allow for pointers
* Remove benchmarks with 250k entities

Use for loop with counter in AoS competition benchmarks

---

CHANGELOG.md
README.md
benchmark/competition/array_of_structs/plot.py

Using pointer iteration in AoS benchmarks improves the runtime of AoS by avoiding copy. Also, it is necessary to change the underlying entites, not only there copies.
This PR replaces the respective plot in the README, as the old information was wrong/biased.

Replace Aos benchmarks plot for pointer iteration fix #284

---

CHANGELOG.md
benchmark/arche/fragmentation/arche_test.go
benchmark/competition/relations/plot.py
benchmark/competition/relations/relation_cached_test.go
benchmark/competition/relations/relation_test.go
benchmark/profile/relations/main.go
ecs/archetype_node.go
ecs/archetypes_test.go
ecs/bitmask.go
ecs/bitmask_test.go
ecs/cache.go
ecs/cache_test.go
ecs/filter.go
ecs/filter_test.go
ecs/query.go
ecs/query_test.go
ecs/relation_examples_test.go
ecs/relation_stress_test.go
ecs/world.go
ecs/world_benchmark_test.go
ecs/world_test.go
examples/relations/main.go
filter/filter.go
filter/filter_test.go
generic/compiled.go
generic/generate/query.go.txt
generic/query_generated.go

* Step back to caching archetypes instead of nodes for filters
* Remove argument `target` from `Filter.Matches`
* Get rid of interface for query archetype list, for faster query construction

Optimize query creation and cached queries

---

CHANGELOG.md
ecs/archetype_node.go
ecs/archetypes.go
ecs/archetypes_test.go
ecs/batch.go
ecs/batch_test.go
ecs/query.go
ecs/relations.go
ecs/world.go
ecs/world_test.go
examples/batch_ops/main.go

Before this change, batchoperations take a callback to provide multiple queries: one for each archetypes.
This PR adds support for multiple batch archetypes in a single query. Batch functions return a query instead of taking a callback.

Return a single query from batch operations

---

CHANGELOG.md
README.md
benchmark/competition/array_of_structs/arche_test.go
ecs/archetype_node.go
ecs/bitmask.go
ecs/bitmask_test.go
ecs/cache.go
ecs/event_test.go
ecs/filter.go
ecs/filter_test.go
ecs/id_map.go
ecs/id_map_test.go
ecs/pool.go
ecs/query_test.go
ecs/util.go
ecs/world_examples_test.go
ecs/world_test.go
filter/filter.go
filter/filter_test.go

Rework `Mask` to hold an array of 4 x `uint64` to represent 256 bits. Everything else comes into place by itself.
Alternative to #312:
- `Filter.Match` takes a mask pointer as argument
- `Mask` is copied when using as a filter (is pointer receiver in #312)
Primarily avoids `All(ids...)` either returning a pointer, or requiring users to store the result (temporarily) to be able to get a pointer to it.
Performance remains unchanged, except that `MaskFilter` matches are about 3 times slower (i.e. filters with component inclusion and exclusion). Not sure why, as the mask functions used there are as fast as before.

Extend to a maximum of 256 component types

---

CHANGELOG.md
ecs/query.go
ecs/query_test.go
ecs/world.go
ecs/world_test.go

Allows users to:
* get `reflect.Type` for component and resource IDs
* get list of components for an entity or for the current query position
Preparation to allow for serialization/deserialization. See #314.

Type and ID getters

---

CHANGELOG.md
ecs/entity.go
ecs/pool.go
ecs/pool_test.go

It uses the space anyway due to padding...

Entity generation changed from unit16 to uint32

---

CHANGELOG.md
README.md
ecs/entity.go
ecs/entity_test.go
ecs/types.go
ecs/world.go
ecs/world_test.go

Allows the world to serialize and deserialize the exact state of all entites (ids, generation, alive; but not components!)
This is required to make it possible to serialize (implicit or explicit) entity relations.
TODO:

Allow to save / load state in terms of assigned entities

---

CHANGELOG.md
ecs/query.go
ecs/world.go

Both return a copy of the archetype's component IDs slice, for safety.
This means that the result can be manipulated safely,
but also that calling the method may incur some significant cost.

Component ID getters in world and query copy ID slice

---

CHANGELOG.md
README.md
ecs/archetype.go
ecs/archetype_node.go
ecs/archetype_test.go
ecs/id_map.go
ecs/registry.go
ecs/registry_test.go
ecs/resources_test.go
ecs/types_test_test.go
ecs/util.go
ecs/util_test.go
ecs/world.go
ecs/world_test.go

Use a growing slice to hold archetype mem layouts, instead of a fixes-size array.
Reduces archetype size from 4 kB to 88 B, plus the heap-allocated slice. The slice starts with size 16 (i.e. 16 component types) and grows in steps of 16 up to 256.

Reduce archetype size by storing layouts in a growing slice

---

CHANGELOG.md
ecs/bitmask_test.go
ecs/event.go
ecs/event_test.go
ecs/world.go
ecs/world_benchmark_test.go
ecs/world_examples_test.go
ecs/world_test.go
examples/change_listener/main.go
generic/exchange.go

* Pass events by value/copy instead of by pointer. It torned out heap escape is much more expensive than copying.
* Removes event fields that are accessible from the world.
* Adds event fields to better identify relation changes.
* Reduces the size of `EntityEvent` by 30%.

Improve `EntityEvent` fields

---

.github/workflows/tests.yml
CHANGELOG.md
doc.go
ecs/batch.go
ecs/event.go
ecs/event/event.go
ecs/event/event_test.go
ecs/event_test.go
ecs/util.go
ecs/world.go
ecs/world_benchmark_test.go
ecs/world_examples_test.go
ecs/world_test.go
examples/change_listener/main.go
listener/callback.go
listener/callback_test.go
listener/dispatched.go
listener/dispatched_test.go
listener/doc.go

* Replaces some fields of `EntityEvent` by a bitmask of triggered event types
* Allows filtering events by a subscriptions mask
* Introduces a `Listener` interface
* Splits out subscriptions and default `Listener` implementation into packages

Listener subscriptions

---

CHANGELOG.md
README.md
doc.go
ecs/bitmask.go
ecs/bitmask_test.go
ecs/doc.go
ecs/event.go
ecs/event/event.go
ecs/event/event_test.go
ecs/event_test.go
ecs/util.go
ecs/util_test.go
ecs/world.go
ecs/world_benchmark_test.go
ecs/world_examples_test.go
ecs/world_test.go
examples/change_listener/main.go
listener/callback.go
listener/callback_test.go
listener/dispatch.go
listener/dispatch_test.go
listener/dispatched.go
listener/dispatched_test.go

* Events are filtered by component IDs in addition to event types
* `Mask` has new methods `And`, `Or` and `Xor`

Listener component subscriptions

---

.github/workflows/benchmarks.yml
.github/workflows/tests.yml
CHANGELOG.md
benchmark/profile/events/main.go
ecs/bitmask.go
ecs/bitmask_64.go
ecs/bitmask_common.go
ecs/bitmask_test.go
ecs/bitmask_tiny.go
ecs/event_test.go
ecs/id_map_test.go
ecs/pool.go
ecs/util.go
ecs/world.go
ecs/world_benchmark_test.go
ecs/world_examples_test.go
ecs/world_test.go
listener/callback.go

Builds with `-tags tiny` reduce the maximum number of component from 256 to 64.
Speeds up mask-related operations and copying of masks, e.g. in the event system.
Adds profiling and more benchmarks for events and listeners.

Build tag `tiny` for max. 64 components

---

CHANGELOG.md
ecs/batch.go
ecs/event.go
ecs/event/event.go
ecs/world.go
ecs/world_event_test.go
ecs/world_internal.go
ecs/world_test.go
listener/dispatch_test.go

* Target is reset to zero when (ex)-changing the relation component
* `RelationChanged` always triggers `TargetChanged`
* Document subscription logic

Fix relation events, reset target on relation change, document subscriptions

---

CHANGELOG.md
ecs/event.go
ecs/functions.go
ecs/functions_test.go
ecs/types_test.go
ecs/world.go
ecs/world_internal.go
ecs/world_test.go

* remove World.ComponentType - replaced by function ComponentInfo
* move public functions and their tests to a separate file
* fix wording of module vs. package in event docs

Cleanup, remove `World.ComponentType`

---

CHANGELOG.md
README.md
generic/compiled.go
generic/generate/main.go
generic/generate/map.go.txt
generic/generate/query.go.txt
generic/map.go
generic/map_generated.go
generic/map_test.go
generic/query_generated.go

* Adds `Map.SetRelationBatch()` and `Map.SetRelationBatchQ()`
* Fixes relations of generic queries returned by batch operations
* Fixes internal field names in generic API for consistency

Generic batch relations

---

ecs/types_test.go

Adds a test to make sure that generic components of the same type but with a different type parameter are treated as a different component type.

Add test for components with generics

---

CHANGELOG.md
ecs/world_internal.go
ecs/world_test.go

Disallows things like these:
```go
e := world.NewEntity(posID, posID) // add the same thing twice
world.Exchange(e, []ID{posID}, []ID{posID}) // add and remove the same thing
```
Which would have caused bugs when used.

Prevent using the same component multiple times in any operations, through panic

---

CHANGELOG.md
ecs/query.go
ecs/query_examples_test.go
ecs/query_test.go
examples/random_sampling/main.go

Adds method `Query.EntityAt()`, useful for things like random sampling of entities.

Query indexing with `EntityAt`

---

ecs/query.go
ecs/world.go

State explicitly that queries can't be re-used, as a lesson learned from #362.

Better document that queries can be iterated only once

---

.github/workflows/benchmarks.yml
BENCHMARKS.md
CHANGELOG.md
README.md
benchmark/table/components.go
benchmark/table/components_batch.go
benchmark/table/entities.go
benchmark/table/entities_batch.go
benchmark/table/main.go
benchmark/table/query.go
benchmark/table/types.go
benchmark/table/util.go

| Operation                        | Time         | Remark                       |
|----------------------------------|-------------:|------------------------------|
| Query.Next                       |       1.0 ns |                              |
| Query.Next + 1x Get              |       1.6 ns |                              |
| Query.Next + 2x Get              |       2.3 ns |                              |
| Query.Next + 5x Get              |       4.4 ns |                              |
| Query.EntityAt, 1 arch           |      11.7 ns |                              |
| Query.EntityAt, 1 arch           |       2.8 ns | registered filter            |
| Query.EntityAt, 5 arch           |      14.9 ns |                              |
| Query.EntityAt, 5 arch           |       3.1 ns | …

Benchmark tables for lookup

---

BENCHMARKS.md
benchmark/table/query.go

`Query.EntityAt` benchmarks did not actually use 5 archetypes, as stated.

Fix `EntityAt` benchmarks to actually use 5 archetypes

---

.github/workflows/tests.yml
CHANGELOG.md
ecs/archetype_test.go
ecs/builder_test.go
ecs/cache.go
ecs/cache_test.go
ecs/doc.go
ecs/pool_test.go
ecs/query.go
ecs/query_debug.go
ecs/query_no_debug.go
ecs/query_test.go
ecs/registry_test.go
ecs/relations_test.go
ecs/resources_test.go
ecs/util_test.go
ecs/world_test.go
generic/map_test.go

* Tests all panics for the concrete error message
* Adds build tag `debug` for better error messages on queries, where we normally rely on out of bounds or nil pointer dereference
* Documents build tags

Better errors, better error tests, build tag `debug`

---

CHANGELOG.md
ecs/archetype.go
ecs/archetype_node.go
ecs/stats/stats.go
ecs/stats/stats_test.go
ecs/world.go
ecs/world_benchmark_test.go

- stats.WorldStats -> stats.World
- stats.EntityStats -> stats.Entities
- stats.NodeStats -> stats.Node
- stats.ArchetypeStats -> stats.Archetype

[breaking] Rename types in `ecs.stats` to remove redundant "Stats"

---

CHANGELOG.md
ecs/archetype_node.go
ecs/types_test.go
ecs/world_test.go

Fix: Do not extend layouts of inactive archetypes

---

ecs/world_event_test.go
ecs/world_internal.go

When calling `Assign()`, listeners get notified of a `ComponentAdded` event after the `exchange()` happens but before the component gets copied. This means that if that component gets fetched in the listener it will be a "zero" component.
The changes in this PR ensure that components are copied before notifying listeners. It splits the internal `exchange()` function into `exchange()`, `exchangeNoNotify()` and `notifyExchange()`.  This allows us to perform the `copyTo()` in the `Assign()` before notifying the listeners.

Ensure Assign() copies components before notifying listeners

---

CHANGELOG.md
benchmark/table/components.go
benchmark/table/entities.go
ecs/builder.go
ecs/world.go
generic/query_test.go

The fix in #438 slows these methods down due to more use of reflection. However, their generic counterparts were optimized in #440 to not use any reflection.
Thus, we deprecate the slow, non-generic methods.

Deprecate slow methods like `World.Assign` and `World.NewEntityWith`

---

CHANGELOG.md
ecs/archetype.go
ecs/builder.go
ecs/relations.go
ecs/world.go
ecs/world_internal.go
ecs/world_test.go
generic/_generate/map.go.txt
generic/map_generated.go

Adds `World.NewEntityFn`, `World.AddFn` and `World.ExchangeFn` that call a callback function before listener notification.
Uses these methods in generic `MapX.NewWith` and `MapX.Assign`.
Fixes #443.

Add callback methods, fix premature notifications issue

---

CHANGELOG.md
ecs/doc.go
go.mod

Retract v0.14.0 due to listener issue #443 and the required additional API (see #445)

Retract v0.14.0

---

CHANGELOG.md
generic/_generate/main.go
generic/map_generated.go

Use `World.GetUnchecked` except for the first assignment.

Optimize MapX.Assign and MapX.NewWith

---

CHANGELOG.md
generic/_generate/map.go.txt
generic/map_generated.go

There were no notifications when called with a relation target.
Documented notification behaviour.

Fix missing listener notification in `MapX.NewWith`

---

CHANGELOG.md
ecs/world_internal.go

Improves performance of `World.Add`, `World.Remove`, `World.Exchange` etc. by around 20ns.

Avoid a heap escape in world component operations (add, remove, exchange)

---

CHANGELOG.md
ecs/archetype.go
ecs/archetype_node.go
ecs/archetype_test.go
ecs/registry.go
ecs/registry_test.go
ecs/resources.go
ecs/types_test.go
ecs/world.go
ecs/world_benchmark_test.go
ecs/world_internal.go
ecs/world_test.go

Zeroing memory of removed components in archetypes to make the GC handle pointers properly takes a significant amount of time. With this change, zeroing is only performed on components for which it is really necessary.
Achieves a speedup of approx. 10-20% for methods that remove entities from or move them between archetypes. Slows down component registration by approx. 40ns per component struct field.
Also introduces separate registry types for components and resources. Speeds up resource type registration by approx. 40ns.

Optimize removal in archetypes

---

CHANGELOG.md
ecs/archetype.go
ecs/archetype_node.go
ecs/archetype_test.go
ecs/registry.go
ecs/registry_test.go
ecs/world_internal.go
ecs/world_test.go

Obviously, #459 was a bit premature. When the un-zeroed memory gets reclaimed, the components of the new or moved entity will take the values of the zombie.

Fix: Undo removal optimization #459

---

CHANGELOG.md
benchmark/profile/exchange_large/main.go
benchmark/table/main.go
ecs/archetype.go
ecs/world_benchmark_test.go
ecs/world_internal.go
ecs/world_test.go

Bulk-copy component data between archetypes on batch operations. As an example, for entities with 10 components, the speedup is 5-10 fold.

Optimize batch-exchange by bulk copying

---

CHANGELOG.md
benchmark/profile/exchange_batch/main.go
ecs/archetype.go
ecs/world_benchmark_test.go

Speeds up batch operations (add, remove, exchange) over entities that previously were in small archetypes.

Speed up reset of small archetypes by zeroing memory manually
